@startuml
(*)  -->"login"
-->"search summaries"
If "find the summary?" then
---> [Yes] "download summary"
If "return to search?" then
--> [   Yes] "search summaries"
else
--> [No] (*)
Endif
else
-----> [ No] "search summaries"
Endif
"search summaries" -> (*)

@enduml