@startuml
(*)  -->[Writer_Upload_Summary] "Downloadable"
"Downloadable"-> [User_Want_To_Read]"Downloaded"
--> [Reader_Think_Unappropraite_Summary] "Reported"
"Reported"-->[Unappropraite_Summary] "Deleted"
"Downloadable"->[Writer_delete_summary] "Deleted"
-->(*)
"Downloaded" -->[Reader_Want_To_Rank] "Ranked"
@enduml